ecommerce/Orders/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import SubmitField, SelectField


class OrderForm(FlaskForm):
    delivery_address = SelectField('addrs')
    buy = SubmitField('Submit')

ecommerce/Orders/routes.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import current_user, login_required
from ecommerce.Orders.forms import OrderForm
from ecommerce.models import products, address, orders, cart
from ecommerce.rmqsender import Sender
from ecommerce import db
from datetime import datetime
from sqlalchemy import and_
import base64

orders_bp = Blueprint('orders', __name__, template_folder="templates")


@orders_bp.route('/details/<pid>/<qty>', methods=['GET', 'POST'])
@login_required
def details(pid, qty):
    if not current_user.is_authenticated:
        return redirect(url_for('users.login'))

    pics = {}
    address_book_usr = {}
    user_address = []
    manufacturer_details = []

    product_price = 0

    prods = products.query.filter_by(product_id=pid).all()
    addrs = address.query.filter_by(user_id=current_user.user_id).all()
    today = datetime.today().strftime('%Y-%m-%d')

    for addr in addrs:
        user_address.append((addr.address_name, addr.complete_address))
        address_book_usr[addr.address_name] = addr.complete_address

    print(current_user.user_id)

    for prod in prods:
        product_pics = []
        product_price = prod.price
        for pic in prod.pics:
            b64data = base64.b64encode(pic).decode('utf-8')
            product_pics.append(b64data)
        pics[prod.product_id] = [prod.product_name, product_pics, prod.description]
        manufacturer_details.append(prod.manufacturer)
        manufacturer_details.append(prod.manufacturer_address)

    orderForm = OrderForm()
    orderForm.delivery_address.choices = [addr for addr in user_address]

    if orderForm.validate_on_submit():
        s = Sender()
        full_addr = address_book_usr[orderForm.delivery_address.data]
        order = orders(user_id=current_user.user_id, product_id=prod.product_id, purchase_date=today,
                       item_name=prod.product_name, sender_address=manufacturer_details[-1],
                       address_name=orderForm.delivery_address.data, delivery_address=full_addr)
        order.order_price = int(qty) * product_price
        order.quantity=int(qty)
        pics[prod.product_id].append(int(qty))
        pics[prod.product_id].append(order.order_price)

        # msg = dict()
        # msg['product_id'] = pid
        # msg['Quantity'] = qty
        # msg['user_id'] = current_user.user_id
        # msg['address'] = orderForm.delivery_address.data
        msg = str(pid)+'-'+str(qty)+'-'+str(current_user.user_id)+'-'+orderForm.delivery_address.data
        # db.session.add(order)
        # db.session.commit()

        # s.publish('product_update', msg)
        return render_template('summary.html', order_details=pics, address=full_addr)

    return render_template('details.html', pictures=pics, form=orderForm, user_address=user_address,
                           manufacturer=manufacturer_details, qty=qty, price=product_price * int(qty))


@orders_bp.route('/summary')
@login_required
def summary():
    return render_template('summary.html')


@orders_bp.route('/checkout', methods=['GET', 'POST'])
@login_required
def checkout():
    user_cart = {}
    address_book_usr = {}
    user_address = []
    manufacturer_details = []
    total_amount = 0

    addrs = address.query.filter_by(user_id=current_user.user_id).all()
    c1 = cart.query.filter_by(user_id=current_user.user_id).all()
    today = datetime.today().strftime('%Y-%m-%d')

    for addr in addrs:
        user_address.append((addr.address_name, addr.complete_address))
        address_book_usr[addr.address_name] = addr.complete_address

    for row in c1:
        prod = products.query.filter_by(product_id=row.product_id).first()
        product_pics = []
        for pic in prod.pics:
            b64data = base64.b64encode(pic).decode('utf-8')
            product_pics.append(b64data)

        total_amount += row.quantity * prod.price
        manufacturer_details.append(prod.manufacturer)
        manufacturer_details.append(prod.manufacturer_address)
        user_cart[row.id] = [row.product_name, product_pics, prod.description, row.quantity, prod.price,
                             manufacturer_details, row.product_id]

    orderForm = OrderForm()
    orderForm.delivery_address.choices = [addr for addr in user_address]
    if orderForm.validate_on_submit():
        full_addr = address_book_usr[orderForm.delivery_address.data]
        for key, val in user_cart.items():
            order = orders(user_id=current_user.user_id, product_id=val[6], purchase_date=today,
                           item_name=val[0], sender_address=val[5][-1],
                           address_name=orderForm.delivery_address.data, delivery_address=full_addr)
            order.order_price = val[3] * val[4]
            order.quantity = val[3]
            product = cart.query.filter(and_(cart.user_id == current_user.user_id, cart.product_name == val[0])).delete()
            db.session.add(order)
            db.session.commit()

        return render_template('summary.html', order_details=user_cart, address=full_addr)

    return render_template('checkout.html', user_cart=user_cart, total_amount=total_amount, form=orderForm)


@orders_bp.route('/history')
@login_required
def history():
    order_history = {}
    user_orders = orders.query.filter_by(user_id=current_user.user_id).order_by(orders.purchase_date.desc()).all()

    for val in user_orders:
        prod = products.query.filter_by(product_id=val.product_id).first()
        product_pics = []
        for pic in prod.pics:
            b64data = base64.b64encode(pic).decode('utf-8')
            product_pics.append(b64data)
        order_history[val.id] = [val.item_name, product_pics, val.quantity, val.id]

    return render_template('history.html', order_history=order_history)


@orders_bp.route('/order_info/<ordid>')
def order_info(ordid):
    order_list = list()
    order = orders.query.filter_by(id=ordid).first()
    prod = products.query.filter_by(product_id=order.product_id).first()
    product_pics = []
    for pic in prod.pics:
        b64data = base64.b64encode(pic).decode('utf-8')
        product_pics.append(b64data)
    order_list.append([order.item_name, product_pics, order.order_price, order.quantity, order.purchase_date.date(), order.delivery_address, prod.manufacturer, prod.manufacturer_address])
    return render_template('order_info.html', val=order_list)

ecommerce/Orders/templates/checkout.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <h1>Checking Out</h1>
        {% for key,val in user_cart.items() %}
       <div>
           <h1>{{ val[0] }}</h1>
             <div class="media-container">
                {% for pic in val[1] %}
                    <img src="data:;base64,{{ pic }}" width="200" height="100">
                {% endfor %}
             </div>
           <h2>{{ val[2] }}</h2>
           <h2>Quantity {{ val[3] }}</h2>
           <h2>Price {{ val[3] * val[4]}}</h2>
       </div>
       <br>
    {% endfor %}
    <h2>Total Amount {{total_amount}}</h2>
        <h3>Deliver to</h3>

    <form class="buy-form" method="POST" action="" enctype="multipart/form-data">
          {{form.csrf_token}}

          <fieldset class="form-field">
              {{ form.delivery_address(class="form-control form-control-lg") }}

          </fieldset>
            <br>

          {{ form.buy(class="btn btn-outline-info") }}
    </form>
</div>
{% endblock %}

ecommerce/Orders/templates/details.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    {% for key,val in pictures.items() %}
       <div>
           <h1>{{ val[0] }}</h1>
             <div class="media-container">
                {% for pic in val[1] %}
                    <img src="data:;base64,{{ pic }}" width="200" height="100">
                {% endfor %}
             </div>
           <h2>{{ val[2] }}</h2>
       </div>
       <br>
    {% endfor %}

    <h3> Total Number of Items {{qty}}</h3>
    <br>

    <h3> Total Amount {{price}} </h3>
    <br>

    <!--<h3>Manufactured by {{manufacturer[0]}} @ {{manufacturer[1]}}</h3>-->

    <h3>Deliver to</h3>

    <form class="buy-form" method="POST" action="" enctype="multipart/form-data">
          {{form.csrf_token}}

          <fieldset class="form-field">
              {{ form.delivery_address(class="form-control form-control-lg") }}

          </fieldset>
            <br>

          {{ form.buy(class="btn btn-outline-info") }}
    </form>
    </div>
</div>
{% endblock %}

ecommerce/Orders/templates/history.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <h3>Your Order history</h3>
    {% for key,val in order_history.items() %}
        <div class="card">
            <div class="row">
                <div class="col-md-4">
                    <img src="data:;base64,{{ val[1][0] }}" width="200" height="100">
                </div>

                <div class="col-md-8">
                    <h3 class="card-title mt-2">{{val[0]}}</h3>
                    <h3 class="card-title mt-2">Quantity : {{val[2]}}</h3>
                    <a href="{{ url_for('orders.order_info',ordid=val[3]) }}">Click to get specific order details</a>
                </div>
            </div>
        </div>
        <br>
    {% endfor %}
</div>
{% endblock %}

ecommerce/Orders/templates/order_info.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <h3>Your Order</h3>
    <img src="data:;base64,{{ val[0][1][0] }}" width="200" height="100">
    <br>
    <h3>Product name: {{val[0][0]}}</h3>
    <br>
    <h3>Product price: {{val[0][2]}}</h3>
    <br>
    <h3>Product price: {{val[0][3]}}</h3>
    <br>
    <h3>Purchase date: {{val[0][4]}}</h3>
    <br>
    <h3>Delivery Address: {{val[0][5]}}</h3>
    <br>
    <h3>Manufactured by: {{val[0][6]}}</h3>
    <br>
    <h3>Manufacturer Address: {{val[0][7]}}</h3>
    <br>
</div>
{% endblock %}

ecommerce/Orders/templates/summary.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <h3>Order Placed successfully</h3>
            {% for key,val in order_details.items() %}
       <div>
           <h3>{{ val[0] }}</h3>
             <div class="media-container">
                {% for pic in val[1] %}
                    <img src="data:;base64,{{ pic }}" width="200" height="100">
                {% endfor %}
             </div>
           <h3>{{ val[2] }}</h3>
           <h3>Quantity {{ val[3] }}</h3>
           <h3>Price {{ val[3] * val[4]}}</h3>
       </div>
       <br>
    {% endfor %}
    <h3>Delivering to {{address}}</h3>
<a href="{{ url_for('general.home') }}">Click to go back to home</a>
</div>
{% endblock %}