ecommerce/Users/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import StringField, EmailField, PasswordField, SubmitField, IntegerField
from wtforms.validators import Length, DataRequired, Email, EqualTo, Regexp


class SignupForm(FlaskForm):
    user_name = StringField('username', [DataRequired(), Length(min=3, max=16)])
    mail = EmailField('usermail', [DataRequired(), Email()])
    password = PasswordField('password', [DataRequired(), Length(min=6, max=16), Regexp("^(?=.*[A-Za-z])(?=.*\\d)(?=.*[$@$!%*#?&])[A-Za-z\\d$@$!%*#?&]{6,16}$")])
    confirm_password = PasswordField('confirmpassword', [DataRequired(), Length(min=6, max=16), EqualTo('password')])
    submit = SubmitField('submit')


class LoginForm(FlaskForm):
    mail = EmailField('usermail', [DataRequired(), Email()])
    password = PasswordField('password', [DataRequired(), Length(min=6, max=16)])
    submit = SubmitField('submit')


class ProfileForm(FlaskForm):
    name = StringField('name', [Length(min=3, max=16)])
    age = IntegerField('age')
    gender = StringField('gender', [Length(min=4, max=20)])
    mail = EmailField('usermail', [Email()])
    submit = SubmitField('submit')


class AddressForm(FlaskForm):
    name = StringField('name')
    building = StringField('building')
    number = StringField('number')
    street = StringField('street')
    landmark = StringField('landmark')
    code = StringField('code')
    city = StringField('city')
    district = StringField('district')
    state = StringField('state')
    country = StringField('country')
    submit = SubmitField('submit')

ecommerce/Users/routes.py
from flask import Blueprint, render_template, url_for, redirect, request,session
from flask_login import login_user, current_user, login_required, logout_user
from ecommerce.Users.forms import SignupForm, LoginForm, ProfileForm, AddressForm
from ecommerce.models import users, address
from ecommerce import db, bcrypt, login_manager

users_bp = Blueprint('user', __name__, template_folder="templates")


@users_bp.route('/signup', methods=['GET', 'POST'])
def signup():
    sform = SignupForm()
    users_count = len(users.query.all())
    if sform.validate_on_submit():
        existing_usr = users.query.filter_by(user_mail=sform.mail.data).first()
        if existing_usr is None:
            u1 = users(user_id=users_count + 1, user_name=sform.user_name.data, user_mail=sform.mail.data,
                       password=bcrypt.generate_password_hash(sform.password.data).decode('utf-8'))
            u1.name = None
            u1.age = 0
            u1.gender = None
            db.session.add(u1)
            db.session.commit()
            login_user(u1)
            return redirect(url_for('general.home'))
        else:
            pass
    return render_template('signup.html', supform=sform)


@users_bp.route('/login', methods=['GET', 'POST'])
def login():
    print(current_user, session)
    if current_user.is_authenticated:
        return redirect(url_for('general.home'))
    lform = LoginForm()
    if lform.validate_on_submit():
        u1 = users.query.filter_by(user_mail=lform.mail.data).first()
        if u1 is not None and bcrypt.check_password_hash(u1.password, lform.password.data):
            print('logging you in')
            login_user(u1)
            print('logged in')
            nxt = request.args.get('next')
            # print(nxt)
            if nxt:
                nxt = nxt[1:]
                return redirect(url_for(nxt))
            return redirect(url_for('general.home'))
        else:
            return redirect(url_for('user.login'))

    return render_template('login.html', linform=lform)


@users_bp.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    print('profile page', current_user.user_mail)
    current_values = [current_user.user_mail, current_user.name, current_user.age, current_user.gender]
    pform = ProfileForm()
    if pform.validate_on_submit():
        if pform.mail.data is not None and pform.mail.data != current_user.user_mail:
            usr = users.query.filter_by(user_mail=pform.mail.data)
            if usr is None:
                print('data changed')
                current_user.user_mail = pform.mail.data
            else:
                print('mail already exists in db try another mail id')

        if pform.name.data is not None and pform.name.data != current_user.name:
            print('data changed name')
            current_user.name = pform.name.data

        if pform.age.data is not None and pform.age.data != current_user.age:
            print('data changed age')
            current_user.age = pform.age.data

        if pform.gender.data is not None and pform.gender.data != current_user.gender:
            print('data changed ')
            current_user.gender = pform.gender.data

        db.session.commit()

    return render_template('profile.html', form=pform, current_values=current_values)


@users_bp.route('/addresses', methods=['GET', 'POST'])
@login_required
def addresses():
    aform = AddressForm()
    address_count = len(address.query.all())
    complete_address = ''
    if aform.validate_on_submit():
        a1 = address(id=address_count + 1, address_name=aform.name.data, building=aform.building.data,
                     number=aform.number.data,
                     street=aform.street.data, landmark=aform.landmark.data, code=aform.code.data,
                     city=aform.city.data, district=aform.district.data, state=aform.state.data,
                     country=aform.country.data)

        for name, val in aform.data.items():
            if val is not '' and name != 'submit' and name != 'csrf_token' and val is not None:
                val += ' '
                complete_address += val

        # a1.complete_address = a1.building+' '+a1.number+' '+a1.street+' '+a1.landmark+' '+a1.code+' '+a1.city+' '+a1.state+' '+a1.country
        a1.complete_address = complete_address
        a1.user_id = current_user.user_id
        db.session.add(a1)
        db.session.commit()
    return render_template('addresses.html', form=aform)


@users_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('user.login'))


@login_manager.unauthorized_handler  # In unauthorized_handler we have a callback URL
def unauthorized_callback():  # In call back url we can specify where we want to
    return redirect(url_for('user.login'))

ecommerce/Users/templates/addresses.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
<form method = 'POST', action="">
    {{form.csrf_token}}
    <fieldset class = 'form-group'>
        <div class = 'form-group'>
            {{form.name.label(class="form-control-label")}}
            {% if form.name.errors %}
                {{form.name(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.name.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{form.name(class="form-control form-control-lg")}}
            {% endif %}
        </div>

        <div class = 'form-group'>
            {{form.building.label(class="form-control-label")}}
            {% if form.building.errors %}
                {{form.building(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.building.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{form.building(class="form-control form-control-lg")}}
            {% endif %}
        </div>

        <div class = 'form-group'>
            {{form.number.label(class="form-control-label")}}
            {% if form.number.errors %}
                {{form.number(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.number.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{form.number(class="form-control form-control-lg")}}
            {% endif %}
        </div>

        <div class = 'form-group'>
            {{form.street.label(class="form-control-label")}}
            {% if form.street.errors %}
                {{form.street(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.street.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{form.street(class="form-control form-control-lg")}}
            {% endif %}
        </div>

        <div class = 'form-group'>
            {{form.landmark.label(class="form-control-label")}}
            {% if form.landmark.errors %}
                {{form.landmark(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.landmark.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{form.landmark(class="form-control form-control-lg")}}
            {% endif %}
        </div>


        <div class = 'form-group'>
            {{form.code.label(class="form-control-label")}}
            {% if form.code.errors %}
                {{form.code(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.code.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{form.code(class="form-control form-control-lg")}}
            {% endif %}
        </div>


        <div class = 'form-group'>
            {{form.city.label(class="form-control-label")}}
            {% if form.city.errors %}
                {{form.city(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.city.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{form.city(class="form-control form-control-lg")}}
            {% endif %}
        </div>


        <div class = 'form-group'>
            {{form.district.label(class="form-control-label")}}
            {% if form.district.errors %}
                {{form.district(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.district.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{form.district(class="form-control form-control-lg")}}
            {% endif %}
        </div>


        <div class = 'form-group'>
            {{form.state.label(class="form-control-label")}}
            {% if form.state.errors %}
                {{form.state(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.state.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{form.state(class="form-control form-control-lg")}}
            {% endif %}
        </div>


        <div class = 'form-group'>
            {{form.country.label(class="form-control-label")}}
            {% if form.country.errors %}
                {{form.country(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.country.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{form.country(class="form-control form-control-lg")}}
            {% endif %}
        </div>


        {{form.submit(class="btn btn-outline-info")}}
    </fieldset>
</form>
    <a href="{{ url_for('user.addresses') }}">Click to modify the address</a>
</div>
{% endblock %}

ecommerce/Users/templates/login.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
<form method = 'POST'>
    {{linform.csrf_token}}
    <fieldset class = 'form-group'>
        <div class = 'form-group'>
            {{linform.mail.label(class="form-control-label")}}
            {% if linform.mail.errors %}
                {{linform.mail(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in linform.mail.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{linform.mail(class="form-control form-control-lg")}}
            {% endif %}
        </div>

        <div class = 'form-group'>
            {{linform.password.label(class="form-control-label")}}
            {% if linform.password.errors %}
                {{linform.password(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in linform.password.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{linform.password(class="form-control form-control-lg")}}
            {% endif %}
        </div>

        {{linform.submit(class="btn btn-outline-info")}}
    </fieldset>
</form>
</div>
{% endblock %}

ecommerce/Users/templates/profile.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
<form method = 'POST', action="">
    {{form.csrf_token}}
    <fieldset class = 'form-group'>
        <div class = 'form-group'>
            {{form.mail.label(class="form-control-label")}}
            {% if form.mail.errors %}
                {{form.mail(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.mail.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{form.mail(class="form-control form-control-lg", value=current_values[0])}}
            {% endif %}
        </div>

        <div class = 'form-group'>
            {{form.name.label(class="form-control-label")}}
            {% if form.name.errors %}
                {{form.name(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.name.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{form.name(class="form-control form-control-lg", value=current_values[1])}}
            {% endif %}
        </div>


        <div class = 'form-group'>
            {{form.age.label(class="form-control-label")}}
            {% if form.age.errors %}
                {{form.age(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.age.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{form.age(class="form-control form-control-lg", value=0)}}
            {% endif %}
        </div>

        <div class = 'form-group'>
            {{form.gender.label(class="form-control-label")}}
            {% if form.gender.errors %}
                {{form.gender(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in form.gender.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{form.gender(class="form-control form-control-lg", value=current_values[3])}}
            {% endif %}
        </div>


        {{form.submit(class="btn btn-outline-info")}}
    </fieldset>
</form>
    <a href="{{ url_for('user.addresses') }}">Click to modify the address</a>
</div>
{% endblock %}

ecommerce/Users/templates/signup.html
{% extends "layout.html" %}

{% block content %}
<div class = 'content-section'>
   <form method = 'POST', action="">
    {{supform.csrf_token}}
    <fieldset class = 'form-group'>
        <div class = 'form-group'>
            {{supform.user_name.label(class="form-control-label")}}
            {% if supform.user_name.errors %}
                {{supform.user_name(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in supform.user_name.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{supform.user_name(class="form-control form-control-lg")}}
            {% endif %}
        </div>

        <div class = 'form-group'>
            {{supform.mail.label(class="form-control-label")}}
            {% if supform.mail.errors %}
                {{supform.mail(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in supform.mail.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{supform.mail(class="form-control form-control-lg")}}
            {% endif %}
        </div>

        <div class = 'form-group'>
            {{supform.password.label(class="form-control-label")}}
            {% if supform.password.errors %}
                {{supform.password(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in supform.password.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{supform.password(class="form-control form-control-lg")}}
            {% endif %}
        </div>

        <div class = 'form-group'>
            {{supform.confirm_password.label(class="form-control-label")}}
            {% if supform.confirm_password.errors %}
                {{supform.confirm_password(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {% for error in supform.confirm_password.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% else %}
                {{supform.confirm_password(class="form-control form-control-lg")}}
            {% endif %}
        </div>

        <div class = 'form-group'>
            {{supform.submit(class="btn btn-outline-info")}}
        </div>

        <div>
            <small class = 'text-muted'>

            </small>
        </div>
    </fieldset>

</form>
</div>

{% endblock %}