ecommerce/Inventory/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed
from wtforms import StringField, IntegerField, SubmitField, MultipleFileField, EmailField, PasswordField
from wtforms.validators import Length, DataRequired, Email, Regexp, EqualTo


class ProductForm(FlaskForm):
    pid = StringField('product_id', [DataRequired()])
    pname = StringField('product_name', [Length(min=2, max=300), DataRequired()])
    manufacturer = StringField('manufacturer', [Length(min=5, max=300), DataRequired()])
    manufacturer_address = StringField('manufacturer_address', [Length(min=5, max=300), DataRequired()])
    description = StringField('description', [Length(min=5, max=300)])
    quantity = IntegerField('quantity')
    pics = MultipleFileField('images', [FileAllowed(['png', 'jpg'])])
    submit = SubmitField('submit')


class SignupForm(FlaskForm):
    admin_name = StringField('adminname', [DataRequired(), Length(min=3, max=16)])
    mail = EmailField('adminmail', [DataRequired(), Email()])
    password = PasswordField('password', [DataRequired(), Length(min=6, max=16), Regexp("^(?=.*[A-Za-z])(?=.*\\d)(?=.*[$@$!%*#?&])[A-Za-z\\d$@$!%*#?&]{6,16}$")])
    confirm_password = PasswordField('confirmpassword', [DataRequired(), Length(min=6, max=16), EqualTo('password')])
    submit = SubmitField('submit')


class LoginForm(FlaskForm):
    mail = EmailField('adminmail', [DataRequired(), Email()])
    password = PasswordField('password', [DataRequired(), Length(min=6, max=16)])
    submit = SubmitField('submit')

ecommerce/General/routes.py
from flask import Blueprint, render_template, url_for, redirect, request, session
from .forms import ProductSearch
from flask_login import current_user

general_bp = Blueprint('general', __name__, template_folder="templates")


@general_bp.route('/home', methods=['GET', 'POST'])
def home():
    # print(request.args)
    # print(session.get('_id'))
    # print(session.get('_user_id'))
    print('loading home', session)
    if hasattr(current_user, 'permission'):
        print('cannot access inventory this page need admin access')
        return redirect(url_for('inventory.inventorylogin'))
    psform = ProductSearch()
    if psform.validate_on_submit():
        return redirect(url_for('products.viewproducts', name=psform.search.data))
    return render_template('home.html', form=psform)

ecommerce/Inventory/routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_user, logout_user, login_required, current_user
from .forms import ProductForm, SignupForm, LoginForm
from ecommerce import db, bcrypt
from ecommerce.models import products, inventoryuser
import base64

inventory_bp = Blueprint('inventory', __name__, template_folder="templates")

""" 
@inventory_bp.route('/inventorysignup', methods=['GET', 'POST'])
def inventorysignup():
    sform = SignupForm()
    if sform.validate_on_submit():
        existing_usr = inventoryuser.query.filter_by(admin_mail=sform.mail.data).first()
        if existing_usr is None:
            u1 = inventoryuser(admin_usr_name=sform.admin_name.data, admin_mail=sform.mail.data,
                               password=bcrypt.generate_password_hash(sform.password.data).decode('utf-8'))
            u1.name = None
            u1.age = 0
            u1.gender = None
            db.session.add(u1)
            db.session.commit()
            login_user(u1)
            return redirect(url_for('inventory.inventory'))
        else:
            pass
    return render_template('inventorysignup.html', supform=sform)


@inventory_bp.route('/inventorylogin', methods=['GET', 'POST'])
def inventorylogin():
    lform = LoginForm()
    if lform.validate_on_submit():
        u1 = inventoryuser.query.filter_by(admin_mail=lform.mail.data).first()
        print(u1.admin_usr_name)
        if u1 is not None and bcrypt.check_password_hash(u1.password, lform.password.data):
            if u1.permission == 'admin':
                print('admin logged in')
                login_user(u1)
                return redirect(url_for('admin.index'))
            else:
                return redirect(url_for('inventory.inventorylogin'))
        else:
            return redirect(url_for('inventory.inventorylogin'))

    return render_template('inventorylogin.html', linform=lform)


@inventory_bp.route('/inventorylogout')
@login_required
def inventorylogout():
    logout_user()
    return redirect(url_for('inventory.inventorylogin'))


@inventory_bp.route('/inventory')
def inventory():
    # query(Model).filter(something).limit(5).all()
    print(current_user.__dict__)
    if not hasattr(current_user, 'permission'):
        print('cannot access inventory this page need admin access')
        return redirect(url_for('inventory.inventorylogin'))
    productList = products.query.limit(5).all()
    pics = {}
    for prods in productList:
        inventory_pics = []
        for prod in prods.pics:
            b64data = base64.b64encode(prod).decode('utf-8')
            inventory_pics.append(b64data)
        pics[prods.product_id] = [prods.product_name, inventory_pics, prods.description]

    return render_template('inventory.html', pictures=pics)


@inventory_bp.route('/addproducts', methods=['GET', 'POST'])
def add_products():
    if not hasattr(current_user, 'permission'):
        print('cannot access add products this page need admin access')
        return redirect(url_for('inventory.inventorylogin'))
    pform = ProductForm()
    if pform.validate_on_submit():
        product_pics = []
        pics = request.files.getlist(pform.pics.name)
        for picture_upload in pics:
            # product_pics.append(secure_filename(picture_upload.filename))
            product_pics.append(picture_upload.stream.read())
        p1 = products(product_id=pform.pid.data, product_name=pform.pname.data,
                      manufacturer=pform.manufacturer.data, manufacturer_address=pform.manufacturer_address.data,
                      pics=product_pics, description=pform.description.data, quantity=pform.quantity.data)

        db.session.add(p1)
        db.session.commit()
        return render_template('addproducts.html', form=pform)

    return render_template('addproducts.html', form=pform)"""

templates/addproducts.html
{% extends 'layout.html' %}


{% block content %}

    <div class="content-section">
      <h2 class="title">Product Form</h2>

      <form method="POST" action="" enctype="multipart/form-data">
          {{form.csrf_token}}

          <fieldset class="form-field">
              {{ form.pid.label }}
              {{ form.pid }}
              {% if form.pid.errors %}
                <ul class="errors">
                    {% for error in form.pid.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
              {% endif %}
          </fieldset>

          <fieldset class="form-field">
              {{ form.pname.label }}
              {{ form.pname }}
              {% if form.pname.errors %}
                <ul class="errors">
                    {% for error in form.pname.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
              {% endif %}
          </fieldset>

          <fieldset class="form-field">
              {{ form.pics.label }}
              {{ form.pics }}
              {% if form.pics.errors %}
                <ul class="errors">
                    {% for error in form.pics.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
              {% endif %}
          </fieldset>


          <fieldset class="form-field">
              {{ form.manufacturer.label }}
              {{ form.manufacturer }}
              {% if form.manufacturer.errors %}
                <ul class="errors">
                    {% for error in form.manufacturer.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
              {% endif %}
          </fieldset>


          <fieldset class="form-field">
              {{ form.manufacturer_address.label }}
              {{ form.manufacturer_address }}
              {% if form.manufacturer_address.errors %}
                <ul class="errors">
                    {% for error in form.manufacturer_address.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
              {% endif %}
          </fieldset>


          <fieldset class="form-field">
              {{ form.quantity.label }}
              {{ form.quantity }}
              {% if form.quantity.errors %}
                <ul class="errors">
                    {% for error in form.quantity.errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
              {% endif %}
          </fieldset>

          {{ form.submit }}

      </form>
    </div>

{% endblock %}

templates/basic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/home.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
<h1>Welcome to the ecommerce site</h1>
</div>
{% endblock %}

templates/inventory.html
{% extends 'layout.html' %}


{% block content %}

    <div class="content-section">
      <h2 class="title">Inventory Page</h2>
    </div>

{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <title>Title</title>
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="">Online Store</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('general.home') }}">Home</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">

            </div>
          </div>
        </div>
      </nav>
    </header>

    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
                {% block content %}{% endblock %}
        </div>
      </div>
    </main>

 <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>