ecommerce/Inventory/routes.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_user, logout_user, login_required, current_user
from .forms import ProductForm, SignupForm, LoginForm
from ecommerce import db, bcrypt
from ecommerce.models import products, inventoryuser
import base64

inventory_bp = Blueprint('inventory', __name__, template_folder="templates")

""" 
@inventory_bp.route('/inventorysignup', methods=['GET', 'POST'])
def inventorysignup():
    sform = SignupForm()
    if sform.validate_on_submit():
        existing_usr = inventoryuser.query.filter_by(admin_mail=sform.mail.data).first()
        if existing_usr is None:
            u1 = inventoryuser(admin_usr_name=sform.admin_name.data, admin_mail=sform.mail.data,
                               password=bcrypt.generate_password_hash(sform.password.data).decode('utf-8'))
            u1.name = None
            u1.age = 0
            u1.gender = None
            db.session.add(u1)
            db.session.commit()
            login_user(u1)
            return redirect(url_for('inventory.inventory'))
        else:
            pass
    return render_template('inventorysignup.html', supform=sform)


@inventory_bp.route('/inventorylogin', methods=['GET', 'POST'])
def inventorylogin():
    lform = LoginForm()
    if lform.validate_on_submit():
        u1 = inventoryuser.query.filter_by(admin_mail=lform.mail.data).first()
        print(u1.admin_usr_name)
        if u1 is not None and bcrypt.check_password_hash(u1.password, lform.password.data):
            if u1.permission == 'admin':
                print('admin logged in')
                login_user(u1)
                return redirect(url_for('admin.index'))
            else:
                return redirect(url_for('inventory.inventorylogin'))
        else:
            return redirect(url_for('inventory.inventorylogin'))

    return render_template('inventorylogin.html', linform=lform)


@inventory_bp.route('/inventorylogout')
@login_required
def inventorylogout():
    logout_user()
    return redirect(url_for('inventory.inventorylogin'))


@inventory_bp.route('/inventory')
def inventory():
    # query(Model).filter(something).limit(5).all()
    print(current_user.__dict__)
    if not hasattr(current_user, 'permission'):
        print('cannot access inventory this page need admin access')
        return redirect(url_for('inventory.inventorylogin'))
    productList = products.query.limit(5).all()
    pics = {}
    for prods in productList:
        inventory_pics = []
        for prod in prods.pics:
            b64data = base64.b64encode(prod).decode('utf-8')
            inventory_pics.append(b64data)
        pics[prods.product_id] = [prods.product_name, inventory_pics, prods.description]

    return render_template('inventory.html', pictures=pics)


@inventory_bp.route('/addproducts', methods=['GET', 'POST'])
def add_products():
    if not hasattr(current_user, 'permission'):
        print('cannot access add products this page need admin access')
        return redirect(url_for('inventory.inventorylogin'))
    pform = ProductForm()
    if pform.validate_on_submit():
        product_pics = []
        pics = request.files.getlist(pform.pics.name)
        for picture_upload in pics:
            # product_pics.append(secure_filename(picture_upload.filename))
            product_pics.append(picture_upload.stream.read())
        p1 = products(product_id=pform.pid.data, product_name=pform.pname.data,
                      manufacturer=pform.manufacturer.data, manufacturer_address=pform.manufacturer_address.data,
                      pics=product_pics, description=pform.description.data, quantity=pform.quantity.data)

        db.session.add(p1)
        db.session.commit()
        return render_template('addproducts.html', form=pform)

    return render_template('addproducts.html', form=pform)"""

ecommerce/Orders/routes.py
from flask import Blueprint, render_template, redirect, url_for
from flask_login import current_user, login_required
from ecommerce.Orders.forms import OrderForm
from ecommerce.models import products, address, orders, cart
from ecommerce.rmqsender import Sender
from ecommerce import db
from datetime import datetime
from sqlalchemy import and_
import base64

orders_bp = Blueprint('orders', __name__, template_folder="templates")


@orders_bp.route('/details/<pid>/<qty>', methods=['GET', 'POST'])
@login_required
def details(pid, qty):
    if not current_user.is_authenticated:
        return redirect(url_for('users.login'))

    pics = {}
    address_book_usr = {}
    user_address = []
    manufacturer_details = []

    product_price = 0

    prods = products.query.filter_by(product_id=pid).all()
    addrs = address.query.filter_by(user_id=current_user.user_id).all()
    today = datetime.today().strftime('%Y-%m-%d')

    for addr in addrs:
        user_address.append((addr.address_name, addr.complete_address))
        address_book_usr[addr.address_name] = addr.complete_address

    print(current_user.user_id)

    for prod in prods:
        product_pics = []
        product_price = prod.price
        for pic in prod.pics:
            b64data = base64.b64encode(pic).decode('utf-8')
            product_pics.append(b64data)
        pics[prod.product_id] = [prod.product_name, product_pics, prod.description]
        manufacturer_details.append(prod.manufacturer)
        manufacturer_details.append(prod.manufacturer_address)

    orderForm = OrderForm()
    orderForm.delivery_address.choices = [addr for addr in user_address]

    if orderForm.validate_on_submit():
        s = Sender()
        full_addr = address_book_usr[orderForm.delivery_address.data]
        order = orders(user_id=current_user.user_id, product_id=prod.product_id, purchase_date=today,
                       item_name=prod.product_name, sender_address=manufacturer_details[-1],
                       address_name=orderForm.delivery_address.data, delivery_address=full_addr)
        order.order_price = int(qty) * product_price
        order.quantity=int(qty)
        pics[prod.product_id].append(int(qty))
        pics[prod.product_id].append(order.order_price)

        # msg = dict()
        # msg['product_id'] = pid
        # msg['Quantity'] = qty
        # msg['user_id'] = current_user.user_id
        # msg['address'] = orderForm.delivery_address.data
        msg = str(pid)+'-'+str(qty)+'-'+str(current_user.user_id)+'-'+orderForm.delivery_address.data
        # db.session.add(order)
        # db.session.commit()

        # s.publish('product_update', msg)
        return render_template('summary.html', order_details=pics, address=full_addr)

    return render_template('details.html', pictures=pics, form=orderForm, user_address=user_address,
                           manufacturer=manufacturer_details, qty=qty, price=product_price * int(qty))


@orders_bp.route('/summary')
@login_required
def summary():
    return render_template('summary.html')


@orders_bp.route('/checkout', methods=['GET', 'POST'])
@login_required
def checkout():
    user_cart = {}
    address_book_usr = {}
    user_address = []
    manufacturer_details = []
    total_amount = 0

    addrs = address.query.filter_by(user_id=current_user.user_id).all()
    c1 = cart.query.filter_by(user_id=current_user.user_id).all()
    today = datetime.today().strftime('%Y-%m-%d')

    for addr in addrs:
        user_address.append((addr.address_name, addr.complete_address))
        address_book_usr[addr.address_name] = addr.complete_address

    for row in c1:
        prod = products.query.filter_by(product_id=row.product_id).first()
        product_pics = []
        for pic in prod.pics:
            b64data = base64.b64encode(pic).decode('utf-8')
            product_pics.append(b64data)

        total_amount += row.quantity * prod.price
        manufacturer_details.append(prod.manufacturer)
        manufacturer_details.append(prod.manufacturer_address)
        user_cart[row.id] = [row.product_name, product_pics, prod.description, row.quantity, prod.price,
                             manufacturer_details, row.product_id]

    orderForm = OrderForm()
    orderForm.delivery_address.choices = [addr for addr in user_address]
    if orderForm.validate_on_submit():
        full_addr = address_book_usr[orderForm.delivery_address.data]
        for key, val in user_cart.items():
            order = orders(user_id=current_user.user_id, product_id=val[6], purchase_date=today,
                           item_name=val[0], sender_address=val[5][-1],
                           address_name=orderForm.delivery_address.data, delivery_address=full_addr)
            order.order_price = val[3] * val[4]
            order.quantity = val[3]
            product = cart.query.filter(and_(cart.user_id == current_user.user_id, cart.product_name == val[0])).delete()
            db.session.add(order)
            db.session.commit()

        return render_template('summary.html', order_details=user_cart, address=full_addr)

    return render_template('checkout.html', user_cart=user_cart, total_amount=total_amount, form=orderForm)


@orders_bp.route('/history')
@login_required
def history():
    order_history = {}
    user_orders = orders.query.filter_by(user_id=current_user.user_id).order_by(orders.purchase_date.desc()).all()

    for val in user_orders:
        prod = products.query.filter_by(product_id=val.product_id).first()
        product_pics = []
        for pic in prod.pics:
            b64data = base64.b64encode(pic).decode('utf-8')
            product_pics.append(b64data)
        order_history[val.id] = [val.item_name, product_pics, val.quantity, val.id]

    return render_template('history.html', order_history=order_history)


@orders_bp.route('/order_info/<ordid>')
def order_info(ordid):
    order_list = list()
    order = orders.query.filter_by(id=ordid).first()
    prod = products.query.filter_by(product_id=order.product_id).first()
    product_pics = []
    for pic in prod.pics:
        b64data = base64.b64encode(pic).decode('utf-8')
        product_pics.append(b64data)
    order_list.append([order.item_name, product_pics, order.order_price, order.quantity, order.purchase_date.date(), order.delivery_address, prod.manufacturer, prod.manufacturer_address])
    return render_template('order_info.html', val=order_list)

ecommerce/Users/routes.py
from flask import Blueprint, render_template, url_for, redirect, request,session
from flask_login import login_user, current_user, login_required, logout_user
from ecommerce.Users.forms import SignupForm, LoginForm, ProfileForm, AddressForm
from ecommerce.models import users, address
from ecommerce import db, bcrypt, login_manager

users_bp = Blueprint('user', __name__, template_folder="templates")


@users_bp.route('/signup', methods=['GET', 'POST'])
def signup():
    sform = SignupForm()
    users_count = len(users.query.all())
    if sform.validate_on_submit():
        existing_usr = users.query.filter_by(user_mail=sform.mail.data).first()
        if existing_usr is None:
            u1 = users(user_id=users_count + 1, user_name=sform.user_name.data, user_mail=sform.mail.data,
                       password=bcrypt.generate_password_hash(sform.password.data).decode('utf-8'))
            u1.name = None
            u1.age = 0
            u1.gender = None
            db.session.add(u1)
            db.session.commit()
            login_user(u1)
            return redirect(url_for('general.home'))
        else:
            pass
    return render_template('signup.html', supform=sform)


@users_bp.route('/login', methods=['GET', 'POST'])
def login():
    print(current_user, session)
    if current_user.is_authenticated:
        return redirect(url_for('general.home'))
    lform = LoginForm()
    if lform.validate_on_submit():
        u1 = users.query.filter_by(user_mail=lform.mail.data).first()
        if u1 is not None and bcrypt.check_password_hash(u1.password, lform.password.data):
            print('logging you in')
            login_user(u1)
            print('logged in')
            nxt = request.args.get('next')
            # print(nxt)
            if nxt:
                nxt = nxt[1:]
                return redirect(url_for(nxt))
            return redirect(url_for('general.home'))
        else:
            return redirect(url_for('user.login'))

    return render_template('login.html', linform=lform)


@users_bp.route('/profile', methods=['GET', 'POST'])
@login_required
def profile():
    print('profile page', current_user.user_mail)
    current_values = [current_user.user_mail, current_user.name, current_user.age, current_user.gender]
    pform = ProfileForm()
    if pform.validate_on_submit():
        if pform.mail.data is not None and pform.mail.data != current_user.user_mail:
            usr = users.query.filter_by(user_mail=pform.mail.data)
            if usr is None:
                print('data changed')
                current_user.user_mail = pform.mail.data
            else:
                print('mail already exists in db try another mail id')

        if pform.name.data is not None and pform.name.data != current_user.name:
            print('data changed name')
            current_user.name = pform.name.data

        if pform.age.data is not None and pform.age.data != current_user.age:
            print('data changed age')
            current_user.age = pform.age.data

        if pform.gender.data is not None and pform.gender.data != current_user.gender:
            print('data changed ')
            current_user.gender = pform.gender.data

        db.session.commit()

    return render_template('profile.html', form=pform, current_values=current_values)


@users_bp.route('/addresses', methods=['GET', 'POST'])
@login_required
def addresses():
    aform = AddressForm()
    address_count = len(address.query.all())
    complete_address = ''
    if aform.validate_on_submit():
        a1 = address(id=address_count + 1, address_name=aform.name.data, building=aform.building.data,
                     number=aform.number.data,
                     street=aform.street.data, landmark=aform.landmark.data, code=aform.code.data,
                     city=aform.city.data, district=aform.district.data, state=aform.state.data,
                     country=aform.country.data)

        for name, val in aform.data.items():
            if val is not '' and name != 'submit' and name != 'csrf_token' and val is not None:
                val += ' '
                complete_address += val

        # a1.complete_address = a1.building+' '+a1.number+' '+a1.street+' '+a1.landmark+' '+a1.code+' '+a1.city+' '+a1.state+' '+a1.country
        a1.complete_address = complete_address
        a1.user_id = current_user.user_id
        db.session.add(a1)
        db.session.commit()
    return render_template('addresses.html', form=aform)


@users_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('user.login'))


@login_manager.unauthorized_handler  # In unauthorized_handler we have a callback URL
def unauthorized_callback():  # In call back url we can specify where we want to
    return redirect(url_for('user.login'))

ecommerce/templates/adminlayout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <title>Title</title>
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{{ url_for('general.home') }}">Online Store Admin Panel</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <!--{% if current_user.is_authenticated %}
              <a class="nav-item nav-link" href="">{{current_user.user_name}}</a>
                {% endif %}-->
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('inventory.inventorylogout') }}">Logout</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>

    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
                {% block content %}{% endblock %}
        </div>
      </div>
    </main>

 <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

ecommerce/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
    <title>Title</title>
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{{ url_for('general.home') }}">Online Store</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <!--{% if current_user.is_authenticated %}
              <a class="nav-item nav-link" href="">{{current_user.user_name}}</a>
                {% endif %}-->
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('orders.history') }}">Order History</a>
                <a class="nav-item nav-link" href="{{ url_for('user.profile') }}">Profile</a>
                <a class="nav-item nav-link" href="{{ url_for('user.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('user.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('user.signup') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>

    <main role="main" class="container">
      <div class="row">
        <div class="col-md-8">
                {% block content %}{% endblock %}
        </div>
      </div>
    </main>

 <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>